version: '3.8'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: gresau/localstack-persist    # Instead of localstack/localstack, to have persisted resources without pro subscription
    ports:
      - "127.0.0.1:4566:4566"           # LocalStack gateway
      - "127.0.0.1:4510-4559:4510-4559" # External services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=eu-central-2
      - SERVICES=s3
      - PERSIST_DEFAULT=0
      - PERSIST_S3=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./my-localstack-data:/persisted-data"
